# Settings of the playground

graphics:
  window_width: 1500 # pixels
  window_height: 1000 # pixels
  scale: 160 # pixels per meter
  black: [20, 20, 40]
  lightblue: [0, 120, 255]
  darkblue: [0, 40, 160]
  red: [255, 100, 0]
  white: [255, 255, 255]
  blue: [0, 0, 255]
  grey: [70, 70, 70]
